spotify_playlist:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('DBT_DATASET')}}"
      location: europe-west1
      project: "{{ env_var('DBT_PROJECT')}}"
      type: bigquery
      method: oauth